blog/config/routes.rb
Blog::Application.routes.draw do

  
 Blog::Application.routes.draw do
 
  resources :posts
 
  root to: "welcome#index"
end

  

end

blog/app/models/post.rb
class Post < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end

  def create
		@post = Post.new(params[:post].permit(:title, :text))
		
		@post.save
		redirect_to @post
	end

	def show
		@post=Post.find(params[:id])	
	end

	private
		def post_params
			params.require(:post).permit(:title,:text)
		end

end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/posts/new.html.erb
<h1> New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
	<p>
		<%= f.label :title %> <br>
		<%= f.text_field :title%>
	</p>
	
	<p> 
		<%= f.label :text %> <br>
		<%= f.text_area :text%>
	</p>
	
	<p>
		<%=f.submit%>
	</p>
<%end%>
	

blog/app/views/posts/show.html.erb
<p>
	<strong>Title:</strong>
  <%= @post.title %>
  
</p>

<p>
	<strong>Text:</strong>
	<%= %>
</p>

blog/app/views/welcome/index.html.erb
<h1>Hello rails!</h1>